name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: HRKU-66cc4c41-8519-4346-84f1-1cca9c499ea5
          heroku_app_name: ba-movies-deploy #Must be unique in Heroku
          heroku_email: j.atiencia@yahoo.com 